package com.example.SmartSeatBackend.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "students")
public class Students {

    // Primary Key (Business Key)
    @Id
    @Column(name = "enrollment_no", nullable = false, unique = true)
    private String enrollmentNo;

    // Auto-generated by DATABASE (BIGSERIAL / IDENTITY)
    @Column(name = "student_id",
            insertable = false,
            updatable = false,
            unique = true)
    private Long studentId;

    private String name;

    @Column(name = "mobile_number")
    private String mobileNumber;

    private String email;

    private String branch;

    private String specialization;

    private Integer semester;

    @ElementCollection
    @CollectionTable(
            name = "subject_student",
            joinColumns = @JoinColumn(name = "enrollment_no")
    )
    @Column(name = "subject_code")
    private List<String> subjects;

    private String password;

    @Column(name = "has_backlog")
    private boolean hasBacklog = false;

    @ElementCollection
    @CollectionTable(
            name = "back_subjects",
            joinColumns = @JoinColumn(name = "enrollment_no")
    )

    private List<String> backlogSubjects;
    @Column(name = "img_url")
    private String imgUrl;

    @Column(name = "college_id")
    private Long collegeId;
}