server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres?sslmode=require
    username: postgres.axxwxwxnqteramwkrwrn
    password: 39UknJkH1SsVc16v
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 3
      minimum-idle: 1
      idle-timeout: 30000
      max-lifetime: 60000
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true



    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: my-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
