server:
  port: 8080
  tomcat:
    max-swallow-size: 10MB
spring:
  ai:
    gemini:
      api-key: ${GEMINI_API_KEY}
      chat:
        options:
          model: gemini-2.0-flash
          temperature: 0.7
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  datasource:
    hikari:
      maximum-pool-size: 3
      minimum-idle: 1
    url: jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres?sslmode=require&prepareThreshold=0
    username: postgres.axxwxwxnqteramwkrwrn
    password: 39UknJkH1SsVc16v
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: my-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
app:
  cloudinary:
    url: cloudinary://256262724346839:hpi0rJYiMi7jP9h9mjCmeWWgSS0@ddlyq5ies
logging:
  level:
    # Disable PDFBox and Fontbox warnings to keep the console clean
    org.apache.pdfbox: OFF
    org.apache.fontbox: OFF
    # Optional: Log the exact HTTP requests to Ollama
    org.springframework.ai.ollama: DEBUG